[colors]
[colors.primary]
foreground = "#F9F7EF"
background = "#191919"
[colors.normal]
black = "#444844"
red = "#D95673"
green = "#8CC06D"
yellow = "#EEBE36"
blue = "#5CAADB"
magenta = "#B594CB"
cyan = "#44A9BA"
white = "#FBFAF7"
[colors.bright]
black = "#6C6D6B"
red = "#DBA1B4"
green = "#898E38"
yellow = "#8A6B3C"
blue = "#126B8B"
magenta = "#7457A1"
cyan = "#87C6D3"
white = "#BFC1BB"
